#!/bin/bash
#SBATCH --partition=GPU
#SBATCH --job-name=Test_Bi-LSTM
#SBATCH --output=run.log
#SBATCH --mail-type=END,FAIL
#SBATCH --mail-user=giovanni.lopez@cimat.mx
cd /home/est_posgrado_giovanni.lopez/Cloud_classification/Scripts
source /opt/anaconda3_titan/bin/activate
conda activate tensorflow
export TF_ENABLE_ONEDNN_OPTS=0
hostname
date
python Test_neural_models.py ratio RS "Bidirectional LSTM" Noroeste
python Test_neural_models.py ratio RS "Bidirectional LSTM" Noreste
python Test_neural_models.py ratio RS "Bidirectional LSTM" Sureste2
python Test_neural_models.py ratio RS "Bidirectional LSTM" Suroeste


python Test_neural_models.py ratio GHI "Bidirectional LSTM" Noroeste
python Test_neural_models.py ratio GHI "Bidirectional LSTM" Noreste
python Test_neural_models.py ratio GHI "Bidirectional LSTM" Sureste2
python Test_neural_models.py ratio GHI "Bidirectional LSTM" Suroeste


python Test_neural_models.py diff GHI "Bidirectional LSTM" Noroeste
python Test_neural_models.py diff GHI "Bidirectional LSTM" Noreste
python Test_neural_models.py diff GHI "Bidirectional LSTM" Sureste2
python Test_neural_models.py diff GHI "Bidirectional LSTM" Suroeste

python Test_neural_models.py diff RS "Bidirectional LSTM" Noroeste
python Test_neural_models.py diff RS "Bidirectional LSTM" Noreste
python Test_neural_models.py diff RS "Bidirectional LSTM" Sureste2
python Test_neural_models.py diff RS "Bidirectional LSTM" Suroeste
date
